baseURL = "https://dazzling-chandrasekhar-3a6a26.netlify.com/"
languageCode = "en-us"
title = "My New Hugo Site"
author = "Alex Wilkins"
description = "Alex Wilkins: Journalist, musician and coder"
# # Enter your tracking code to enable Google Analytics
# googleAnalytics = ""
disqusShortname = "www-alex-wilkins-com"
copyright = "Copyright © 2019, Alex Wilkins; all rights reserved."
canonifyURLS = true
paginate = 12
