baseURL = "https://alexwilkins-3a6a26.netlify.com/"
languageCode = "en-us"
title = "My New Hugo Site"
description = "Alex Wilkins: Journalist, musician and coder"
tags = ["blog", "sidebar", "SEO"]
# # Enter your tracking code to enable Google Analytics
# googleAnalytics = ""
disqusShortname = "www-alex-wilkins-com"
copyright = "Copyright © 2019 Alex Wilkins."
canonifyURLS = true
paginate = 12
redirects= "https://alexwilkins.netlify.com/* https://www.alex-wilkins.com/:splat 301!"


[params]
	author = "Alex Wilkins"
        bio = "Alex Wilkins: Journalist, musician and coder"
	logo = "/images/favicon.png"
	avatar = "/images/logo.ico"
	opengraphImage = "/images/favicon.png"
  readMore = "Read more"

    # Social
	twitter  = "https://twitter.com/AlexWilkins22"
	github   = "https://github.com/AlexWilkins19"
	facebook  = ""
  linkedin  = "https://www.linkedin.com/in/alex-wilkins-345077117/"


    # Code highlighting with highlight.js
    highlightJS = true

# Taxonomies
[taxonomies]
    tag = "tags"
