name: Update Portfolio

on:
  schedule:
    - cron: '0 0 * * *' # This will run the workflow every day at midnight (00:00)
  workflow_dispatch: # This line enables the manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run the scraping script
      run: node scrape-articles.js

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run the conversion script
      run: python markdownfiles.py

    - name: Install Hugo
      run: |
        HUGO_VERSION="0.93.1"
        echo "Installing Hugo $HUGO_VERSION"
        curl -sSL https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz && \
        sudo tar -xzf /tmp/hugo.tar.gz -C /usr/local/bin && \
        sudo chmod +x /usr/local/bin/hugo && \
        rm -f /tmp/hugo.tar.gz
      env:
        HUGO_VERSION: 0.93.1

    - name: Build Hugo site
      run: hugo

    - name: Commit and push changes
      run: |
        git config --global user.name "Alex Wilkins"
        git config --global user.email "zanderwilkins19@gmail.com"
        git add .
        git commit -m "Update portfolio articles"
        git push
