name: Update Portfolio
on:
  schedule:
    - cron: '0 0 * * *'  # Fixed cron syntax
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    # Add permissions for GitHub token
    permissions:
      contents: write
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run the scraping script
        run: node scrape-articles.js

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run the conversion script
        run: python markdownfiles.py

      - name: Install Hugo
        run: |
          HUGO_VERSION="0.83.1"
          echo "Hugo version: $HUGO_VERSION"
          curl -fsSL https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz | tar xz
          sudo mv hugo /usr/local/bin/

      - name: Build Hugo site
        run: hugo

      - name: Commit and push changes
        run: |
          git config --global user.name "Alex Wilkins"
          git config --global user.email "zanderwilkins19@gmail.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update portfolio articles"
            git push
          fi
