name: Update Portfolio

on:
  schedule:
    - cron: '0 0 * * *' # This will run the workflow every day at midnight (00:00)
  workflow_dispatch: # This line enables the manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Run the scraping script
      run: node scrape-articles.js

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run the conversion script
      run: python markdownfiles.py

    - name: Build Hugo site
      run: hugo

    - name: Commit and push changes
      run: |
        git config --global user.name "Alex Wilkins"
        git config --global user.email "zanderwilkins19@gmail.com"
        git add .
        git commit -m "Update portfolio articles"
        git push
